services:
  mysql:
    image: mysql:8.0
    container_name: bird-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: birds
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: bird-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/birds
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./client
    container_name: bird-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
